# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Aurelia CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
defaults:
  run:
    working-directory: './'
    
jobs:
  setup:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    
    - name: Checkout submodules
      run: git submodule update --init --recursive
          
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'# Set always-auth in npmrc.
        cache-dependency-path: './package-lock.json'
    #- run: npm ci
    #- run: npm run build --if-present
    #- run: npm test
    
    - run: npm install
    - name: Build Aurelia
      run: |
        npm run build
    
    # remove scraped (images are heavy to deploy)
    - run: rm -rf "/home/runner/work/encyclofus/encyclofus/src/DofusDB/scraped/"
    # remove test folder
    - run: rm -rf "/home/runner/work/encyclofus/encyclofus/test/"
    # remove src folder
    - run: rm -rf "/home/runner/work/encyclofus/encyclofus/src/"
    # remove all files in the root directory (not folders)
    - run: ls
    - run: find "/home/runner/work/encyclofus/encyclofus/" -maxdepth 1 -type f -delete
    - run: ls
    # move files from dist to root
    - run: mv dist/* .


    - name: Deploy to branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: "/home/runner/work/encyclofus/encyclofus"
